### ISSUE TITLE
Are you on discord?

### ISSUE THREAD

**Issue by Jeb0978** [saintly2k/aniZero#1]
.

**Comment by saintly2k** [comment]
sorry for the late reply, i didnt see it.

yes, i am ln discord: $aintly#2000

**Comment by saintly2k** [comment]
just close the ticket when you've added me or so :)

**Comment by Jeb0978** [comment]
Oh alr 👍

**Comment by forseyq** [comment]
> sorry for the late reply, i didnt see it.
> 
> yes, i am ln discord: $aintly#2000

@saintly2k  ur nitro expired or something whats ur new tag lol

**Comment by saintly2k** [comment]
yeah, just was about to tell ya, this is my new discord: $aintly#0394

**Comment by saintly2k** [comment]
@forseyq

**Comment by forseyq** [comment]
thx
